# --- !Ups

CREATE TABLE "people" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null
);
--insert into people (name, age) values ('Tom', 20);

CREATE TABLE "users" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "age" int not null
);
--insert into users (name, age) values ('George', 35);

CREATE TABLE "tasks" (
  task_id VARCHAR(50) NOT NULL,
  name VARCHAR(100) NOT NULL,
  state VARCHAR(20) NOT NULL,
  author_id VARCHAR(50) NOT NULL,
  assignee_id VARCHAR(50),
  version INT NOT NULL,
  PRIMARY KEY (task_id)
);

CREATE TABLE "task_comments" (
  task_comment_id VARCHAR(50) NOT NULL,
  task_id VARCHAR(50) NOT NULL,
  message VARCHAR(200) NOT NULL,
  commenter_id VARCHAR(50) NOT NULL,
  PRIMARY KEY (task_comment_id)
);

# --- !Downs

drop table "people" if exists;
drop table "users" if exists;
drop table "tasks" if exists;
drop table "task_comments" if exists;
